/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  // customSidebar: [
  //   {
  //     type: "doc",
  //     id: "introduction",
  //     label: "Introduction to Defactor",
  //   },
  //   {
  //     type: "category",
  //     label: categoryJsonBCW3.label,
  //     link: categoryJsonBCW3.link,
  //     items: [
  //       "blockchain-and-web3/ethereum",
  //       "blockchain-and-web3/polygon",
  //       "blockchain-and-web3/algorand",
  //     ],
  //   },
  //   {
  //     type: "category",
  //     label: categoryJsonSC.label,
  //     link: categoryJsonSC.link,
  //     items: [
  //       {
  //         type: "category",
  //         label: categoryJsonPoolsC.label,
  //         link: categoryJsonPoolsC.link,
  //         items: [
  //           "smart-contracts/pools-contract/smart-contract-erc20-collateral-pool",
  //           "smart-contracts/pools-contract/smart-contract-erc20-collateral-pool-technical-aspects",
  //           "smart-contracts/pools-contract/smart-contract-erc20-collateral-pool-example",
  //         ],
  //       },
  //       {
  //         type: "category",
  //         label: categoryJsonERC20C.label,
  //         link: categoryJsonERC20C.link,
  //         items: [
  //           "smart-contracts/erc20-collateral-pool-contract/smart-contract-erc20-collateral-pool",
  //           "smart-contracts/erc20-collateral-pool-contract/smart-contract-erc20-collateral-pool-technical-aspects",
  //           "smart-contracts/erc20-collateral-pool-contract/smart-contract-erc20-collateral-pool-example",
  //         ],
  //       },
  //       {
  //         type: "category",
  //         label: categoryJsonStakingC.label,
  //         link: categoryJsonStakingC.link,
  //         items: [
  //           "smart-contracts/staking-contract/smart-contract-staking-technical-aspects",
  //         ],
  //       },
  //     ],
  //   },
  //   {
  //     type: "category",
  //     label: categoryJsonApi.label,
  //     link: categoryJsonApi.link,
  //     items: [
  //       {
  //         type: "category",
  //         label: categoryJsonEngage.label,
  //         link: categoryJsonEngage.link,
  //         items: [
  //           "api/engage/listProposals",
  //           "api/engage/getProposalDetails",
  //           "api/engage/listVotes",
  //           "api/engage/getKyc",
  //           "api/engage/startKyc",
  //           "api/engage/addKycWallet",
  //           "api/engage/insertUserVote",
  //           "api/engage/circulatingSupply",
  //         ],
  //       },
  //       {
  //         type: "category",
  //         label: categoryJsonPools.label,
  //         link: categoryJsonPools.link,
  //         items: [
  //           "api/pools/listPools",
  //           "api/pools/insertPool",
  //           "api/pools/initiateUpload",
  //         ],
  //       },
  //       {
  //         type: "category",
  //         label: categoryJsonERC20.label,
  //         link: categoryJsonERC20.link,
  //         items: ["api/erc20CollateralToken/default"],
  //       },
  //     ],
  //   },
  //   {
  //     type: "category",
  //     label: categoryJsonFE.label,
  //     link: categoryJsonFE.link,
  //     items: [
  //       "front-end-ui/general-features",
  //       "front-end-ui/components",
  //       "front-end-ui/example-sites",
  //     ],
  //   },
  //   {
  //     type: "category",
  //     label: categoryJsonRWUC.label,
  //     link: categoryJsonRWUC.link,
  //     items: [
  //       "rwa-use-cases/index",
  //       {
  //         type: "category",
  //         label: categoryJsonLeaseA.label,
  //         link: categoryJsonLeaseA.link,
  //         items: [
  //           "rwa-use-cases/lease-agreement/lease-agreement-outline",
  //           "rwa-use-cases/lease-agreement/lease-agreement-api",
  //           "rwa-use-cases/lease-agreement/lease-agreement-database",
  //           "rwa-use-cases/lease-agreement/lease-agreement-use-case",
  //         ],
  //       },
  //       {
  //         type: "category",
  //         label: categoryJsonAurus.label,
  //         link: categoryJsonAurus.link,
  //         items: [
  //           "rwa-use-cases/aurus/rwa-use-case-aurus-overview",
  //           "rwa-use-cases/aurus/rwa-use-case-aurus",
  //         ],
  //       },
  //     ],
  //   },
  //   {
  //     type: "category",
  //     label: categoryJsonRsc.label,
  //     link: categoryJsonRsc.link,
  //     items: [
  //       "resources/additional-resources",
  //       "resources/roadmap",
  //       "resources/faqs",
  //       "resources/glossary",
  //     ],
  //   },
  // ],
};

export default sidebars;
